### ISSUE TITLE
ConstantLike op should be foldable

### ISSUE THREAD

**Issue by aborgna-q** [CQCL-DEV/hugr-mlir#8]
Currently, trying to call `hugr-mlir-opt` on any example mlir produced by `guppy-runner` errors out with the following message:

```
hugr-mlir-opt: /build/mlir-src-18.0.0-git-1a8b36b/mlir/include/mlir/IR/Matchers.h:92:
    bool mlir::detail::constant_op_binder<AttrT>::match(mlir::Operation*) [with AttrT = mlir::Attribute]:
    Assertion `succeeded(result) && "expected ConstantLike op to be foldable"' failed.
```

**Comment by doug-q** [comment]
Indeed it should, this is resolved in develop by removing `ConstantLike` from `hugr.load_constant`. True constants are rewritten to the (implementation detail op) `hugr.constant` which does have `ConstantLike` and is foldable.
